name: Mantener Supabase Activo

on:
  schedule:
    # Se ejecuta todos los días a las 05:00 AM UTC y 17:00 PM UTC
    - cron: '0 5,17 * * *'
  workflow_dispatch: # Permite probarlo manualmente cuando quieras

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer consulta a Supabase
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}")
          
          echo "Supabase devolvió el código HTTP: $STATUS"
          
          if [ "$STATUS" -eq 200 ] || [ "$STATUS" -eq 300 ]; then
            echo "Conexión exitosa a la base de datos."
          else
            echo "Error en la consulta HTTP $STATUS"
            exit 1
          fi
